[package]
name = "ruizukun-dev/nature2d"
description = "Create versatile physics simulations and mechanics with Guis on Roblox!"
version = "0.7.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["assets", "docs", "unit-test", "LICENSE"]

[dependencies]
